 hosts: all
 roles:
  - role: elastic.beats
 vars:
  beats_version: 7.12.0
  beat: filebeat
  beat_conf:
    filebeat:
      inputs:
        - type: log
          enabled: true
          paths:
            - /var/log/*.log
    output_conf : {
        "elasticsearch": {
          "hosts": ["192.168.1.232:9200"]}}
